version: "2"
linters:
  enable:
    - bodyclose
    - exhaustive
    - gocritic
    - misspell
    - nilerr
    - nilnil
    - noctx
    - paralleltest
    - revive
    - sqlclosecheck
    - tparallel
    - usetesting
    - wastedassign
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
