name: test

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Set up Go
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
      with:
        go-version-file: 'go.mod'

    - name: Run tests
      run: go test ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@9fae48acfc02a90574d7c304a1758ef9895495fa # v7

    - name: Check Go Modules Tidy
      run: |
        echo "Running go mod tidy..."
        go mod tidy
        echo "go mod tidy finished."

    - name: Check for uncommitted changes
      run: |
        git_status=$(git status --porcelain)
        if [ -n "$git_status" ]; then
          echo "::error::Uncommitted changes detected after build and tests."
          echo "::group::Git Status"
          echo "$git_status"
          echo "::endgroup::"
          echo "::group::Git Diff"
          git diff --color=always
          echo "::endgroup::"
          exit 1
        else
          echo "No uncommitted changes found."
        fi

